version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole-01
    image: pihole/pihole:latest
    hostname: jfrx-pihole-server-01
    container_name: pihole
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole-01.entrypoints=http"
      - "traefik.http.routers.pihole-01.rule=Host(`pihole.s01.local.cf`)"  
      - "traefik.http.services.pihole-01.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole-01.middlewares=pihole-01-admin"
      - "traefik.http.middlewares.pihole-01-admin.addprefix.prefix=/admin"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      TZ: 'Asia/Kuala_Lumpur'
      WEBPASSWORD: '*****'
      DNSSEC: 'true'
      DNSMASQ_LISTENING: 'single'
    volumes:
      - '/DockerFile/Pihole/pihole-data/:/etc/pihole/'
      - '/DockerFile/Pihole/dnsmasq-data/:/etc/dnsmasq.d/'
    restart: unless-stopped
networks:
  web:
    external: true
