version: "3.3"

services:
  traefik:
    image: traefik:latest
    restart: always
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    command:
      - --configFile=/config/traefik.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # <== Volume for docker admin
      - ./config:/config
      - ./certs:/certs
    networks:
      - web # <== Placing traefik on the network named web, to access containers on this network
    # labels:
      # - "traefik.enable=true"
      # # Dashboard
      # - "traefik.http.routers.traefik.service=api@internal"
      # - "traefik.http.routers.traefik.tls=true"
      # - "traefik.http.routers.traefik.entrypoints=https"
      # - "traefik.http.routers.traefik.rule=Host(`traefik.local.cf`)"
      # - "traefik.http.routers.traefik.middlewares=authelia@docker"
      # Redirect http to https
      # - "traefik.http.routers.http-catchall.rule=hostregexp(\"{host:.+}\")"
      # - "traefik.http.routers.http-catchall.entrypoints=https"
      # - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # Metrics
      # - "traefik.http.routers.traefik-metrics.service=traefik-metrics"
      # - "traefik.http.routers.traefik-metrics.tls=true"
      # - "traefik.http.routers.traefik-metrics.entrypoints=https"
      # - "traefik.http.services.traefik-metrics.loadbalancer.server.port=5043"
      # - "traefik.http.routers.traefik-metrics.rule=Host(`traefik.jiro.dev`) && Path(\"/metrics\")"
networks:
  web:
    external: true
