
# Global Config
global:
  checkNewVersion: false
  sendAnonymousUsage: true

# Entrypoints
entryPoints:
  http:
    address: :80
  https:
    address: :443
api:
  dashboard: true
  insecure: false
  debug: true
# accessLog: {}
log:
  level: DEBUG
providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
    network: web
  file:
    filename: /config/dyn.yml
    watch: true
# serversTransport:
  # insecureSkipVerify: true
defaultEntryPoints:
  - https
  - http
