version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - WEBUI_PORT=8080
    volumes:
      - /mnt/random/docker-file/qbittor:/config
      - /mnt/grey/tor:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
