version: "3"

services:
  api:
    image: vikunja/api
    container_name: vikunja-api
    environment:
      - TZ=Asia/Kuala_Lumpur
      - VIKUNJA_SERVICE_FRONTENDURL=https://task.local.cf
    volumes:
      - /DockerFile/Vikunja/files/:/app/vikunja/files
      - ./config.yml:/app/vikunja/config.yml
    restart: unless-stopped
    networks:
      - database
      - redis
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vikunja_api.entrypoints=http"
      - "traefik.http.routers.vikunja_api.rule=Host(`task.local.cf`) && PathPrefix(`/api/v1`, `/dav/`, `/.well-known/`)"
      # - "traefik.http.routers.vikunja_api.tls=true"
      - "traefik.http.services.vikunja_api.loadbalancer.server.port=3456"

  front-end:
    image: vikunja/frontend
    container_name: vikunja-front-end
    depends_on:
      - api
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vikunja_frontend.rule=Host(`task.local.cf`)"
      # - "traefik.http.routers.vikunja_frontend.tls=true"
      - "traefik.http.routers.vikunja_frontend.entrypoints=http"
      - "traefik.http.services.vikunja_frontend.loadbalancer.server.port=80"
      # - 'traefik.http.routers.vikunja_frontend.middlewares=authelia@docker'
    networks:
      - web

networks:
  web:
    external: true
  database: 
    external: true
  redis:
    external: true
