version: "3"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./redis.conf:/etc/redis.conf
    networks: 
      - redis
    command: ["redis-server", "/etc/redis.conf"]
networks:
  redis:
    external: true
